# Generated by Django 5.2.3 on 2025-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="average price",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="product",
            name="default_unit",
            field=models.CharField(
                choices=[
                    ("count", "Count"),
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("l", "Liters"),
                    ("oz", "Ounces"),
                    ("lb", "Pounds"),
                ],
                default="count",
                max_length=10,
                verbose_name="default unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, verbose_name="ingredients"),
        ),
        migrations.AddField(
            model_name="product",
            name="packaging",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="packaging"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_days",
            field=models.IntegerField(
                blank=True,
                help_text="Typical shelf life in days",
                null=True,
                verbose_name="shelf life (days)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="e.g., openfoodfacts, upcitemdb, manual",
                max_length=50,
                verbose_name="data source",
            ),
        ),
    ]
