# Generated by Django 5.2.3 on 2025-06-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_average_price_product_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="image URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True, verbose_name="thumbnail URL"),
        ),
    ]
