# Generated by Django 5.2.3 on 2025-06-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_product_image_url_alter_product_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="country",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, default="", verbose_name="ingredients"),
        ),
        migrations.AlterField(
            model_name="product",
            name="packaging",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="packaging"
            ),
        ),
    ]
