# Generated by Django 5.2.3 on 2025-06-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_product_country_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="local_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="local image"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="local_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/thumbs/",
                verbose_name="local thumbnail",
            ),
        ),
    ]
