# Generated by Django 5.2.3 on 2025-06-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_product_search_vector_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_search__7bdc4d_gin",
        ),
        migrations.RemoveField(
            model_name="product",
            name="search_vector",
        ),
    ]
