# Generated by Django 5.2.3 on 2025-06-22 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_product_products_search__7bdc4d_gin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="current_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="current quantity",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="minimum_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="minimum threshold",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="purchase price",
            ),
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="barcode_type",
            field=models.CharField(
                choices=[
                    ("EAN13", "EAN-13"),
                    ("UPC", "UPC"),
                    ("Code128", "Code 128"),
                    ("QR", "QR Code"),
                ],
                default="EAN13",
                max_length=20,
                verbose_name="barcode type",
            ),
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="is verified"),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="temperature_max",
            field=models.FloatField(
                blank=True, null=True, verbose_name="maximum temperature (°C)"
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="temperature_min",
            field=models.FloatField(
                blank=True, null=True, verbose_name="minimum temperature (°C)"
            ),
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("refrigerator", "Refrigerator"),
                    ("fridge", "Refrigerator"),
                    ("freezer", "Freezer"),
                    ("pantry", "Pantry"),
                    ("counter", "Counter"),
                    ("cabinet", "Cabinet"),
                    ("other", "Other"),
                ],
                default="pantry",
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.DeleteModel(
            name="ShoppingListItem",
        ),
    ]
