# Generated by Django 5.2.3 on 2025-07-22 22:20

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_inventoryitem_price_and_more"),
    ]

    operations = [
        # Enable trigram extension for fuzzy text search
        TrigramExtension(),
        # Enable unaccent extension for better text matching  
        UnaccentExtension(),
    ]
