# Generated by Django 5.2.3 on 2025-06-22 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipetag_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.IntegerField(
                default=0,
                help_text="Time to cook the recipe",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="cooking time (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(
                default=0,
                help_text="Time to prepare ingredients",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="preparation time (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time including prep and cook",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="total time (minutes)",
            ),
        ),
    ]
