# Generated by Django 5.2.3 on 2025-06-22 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_cook_time_alter_recipe_prep_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="average_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="average rating",
            ),
        ),
        migrations.AddField(
            model_name="userrecipeinteraction",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AddField(
            model_name="userrecipeinteraction",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AddField(
            model_name="userrecipeinteraction",
            name="times_cooked",
            field=models.IntegerField(default=0, verbose_name="times cooked"),
        ),
    ]
