# Generated by Django 5.2.3 on 2025-06-22 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_average_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="step_number",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="step number",
            ),
        ),
    ]
