# Generated by Django 5.2.3 on 2025-06-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringshoppingitem",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_shopping_items",
                to="accounts.household",
            ),
        ),
    ]
