# Generated by Django 5.2.3 on 2025-06-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_recurringshoppingitem_household"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="store name"
            ),
        ),
    ]
