# Generated by Django 5.2.3 on 2025-06-22 19:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_alter_store_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="budget_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="budget limit",
            ),
        ),
    ]
